In [ ]:
import numpy as np 
import pandas as pd

In [ ]:
df = pd.read_csv('Titanic-Dataset.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.head() # First 5 rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.tail(10) # Last 10 rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df.sample(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
503,504,0,3,"Laitinen, Miss. Kristina Sofia",female,37.0,0,0,4135,9.5875,NaN,S
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
393,394,1,1,"Newell, Miss. Marjorie",female,23.0,1,0,35273,113.2750,D36,C

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
med_age = df['Age'].median() #find median of age 
df['Age'] = df['Age'].fillna(med_age) # fill null age entity with median value of age
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df['Embarked'].value_counts() # to know which value from embarked is most common to fll tnto missing

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [ ]:
df['Embarked'] = df['Embarked'].fillna('S')
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [ ]:
df.drop(columns=['Cabin', 'Ticket']) #Cabin is mostly empty, and Ticket is just a random string of numbers that an AI can't easily learn from, drop them entirely

KeyError: "['Cabin', 'Ticket'] not found in axis"

In [ ]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [ ]:
# Add $5 to every Fare
df['Fare'] = df['Fare'] + 5

# Check the first few rows to see the updated Fares
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,12.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,76.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,12.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,58.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,13.0500,S

In [ ]:
# Extract all details for passenger 10
passenger_10 = df.loc[10]
passenger_10

PassengerId                                 11
Survived                                     1
Pclass                                       3
Name           Sandstrom, Miss. Marguerite Rut
Sex                                     female
Age                                        4.0
SibSp                                        1
Parch                                        1
Fare                                      21.7
Embarked                                     S
Name: 10, dtype: object

In [ ]:
male_survivors = df[(df['Sex'] == 'male') & (df['Survived'] == 1)]

# Display the first 5 male survivors
male_survivors.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Embarked
17,18,1,2,"Williams, Mr. Charles Eugene",male,28.0,0,0,18.0000,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,18.0000,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,40.5000,S
36,37,1,3,"Mamee, Mr. Hanna",male,28.0,0,0,12.2292,C
55,56,1,1,"Woolner, Mr. Hugh",male,28.0,0,0,40.5000,S

In [ ]:
# Filter for specific ports
c_or_q_ports = df[df['Embarked'].isin(['C', 'Q'])]

c_or_q_ports.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,76.2833,C
5,6,0,3,"Moran, Mr. James",male,28.0,0,0,13.4583,Q
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,35.0708,C
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,34.1250,Q
19,20,1,3,"Masselmani, Mrs. Fatima",female,28.0,0,0,12.2250,C

In [ ]:
# Find names containing "Miss." unmarried
miss_passengers = df[df['Name'].str.contains('Miss.', na=False)]

miss_passengers.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Embarked
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,12.9250,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,21.7000,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,31.5500,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,12.8542,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,13.0292,Q

In [ ]:
# Create FamilySize column
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1

# Check the new column
df[['Name', 'SibSp', 'Parch', 'FamilySize']].head()

                                                Name  SibSp  Parch  FamilySize
0                            Braund, Mr. Owen Harris      1      0           2
1  Cumings, Mrs. John Bradley (Florence Briggs Th...      1      0           2
2                             Heikkinen, Miss. Laina      0      0           1
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)      1      0           2
4                           Allen, Mr. William Henry      0      0           1

In [ ]:
# Create Fare_Per_Person column
df['Fare_Per_Person'] = df['Fare'] / df['FamilySize']

df[['Name', 'Fare', 'FamilySize', 'Fare_Per_Person']].head()

,Name,Fare,FamilySize,Fare_Per_Person
0,"Braund, Mr. Owen Harris",12.2500,2,6.12500
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",76.2833,2,38.14165
2,"Heikkinen, Miss. Laina",12.9250,1,12.92500
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",58.1000,2,29.05000
4,"Allen, Mr. William Henry",13.0500,1,13.05000